# Example  .gitlab-ci.yml file
stages:
  - mavenbuild
  - maventest
  - mavenDeploy
  - androidbuild
  - androidtest

maven-build:
  stage: mavenbuild
  tags:
    - springboot_tag
  script:
    - cd Backend/WorkoutList
    - mvn package
    
maven-test:
  stage: maventest
  tags:
    - springboot_tag
  script:
    - cd Backend/WorkoutList
    - mvn test
  artifacts:
    paths:
      - Backend/target/*.jar

android-build:
  image: gjandres/android-ci:latest
  stage: androidbuild
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./Frontend/gradlew
  tags:
   - android_tag
  script:
    - cd Frontend
    - ./gradlew build
  artifacts:
    paths:
    - Android_test/app/build/outputs/

android-test:
  image: gjandres/android-ci:latest
  stage: androidtest
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./Frontend/gradlew
  tags:
   - android_tag
  script:
    - cd Frontend
    - ./gradlew test

# This job builds, deploys, executes jar as service.
autoDeploy:
  stage: mavenDeploy  #do make a stage with same name!
  tags:
   - springboot_tag   #do have a runner with same tag
  rules:
   - if: $CI_COMMIT_BRANCH == "main"
  script:
    - cd Backend/WorkoutList
    - mvn package
    - sudo mv target/*.jar /target/web-demo.jar 
    - sudo systemctl stop system-web-demo
    - sudo systemctl start system-web-demo
  


jayden-android-build:
  image: gjandres/android-ci:latest
  stage: androidbuild
  tags:
    - android_tag
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./Frontend/gradlew
  script:
    - cd Frontend
    - ./gradlew assembleDebug
    - mkdir -p artifacts
    - cp app/build/outputs/apk/debug/app-debug.apk artifacts/
  artifacts:
    paths:
      - artifacts/

